language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.2

before_install:
  	- chmod +x gradlew

before_script:
  	# Create and start emulator
	- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
	- emulator -avd test -no-skin -no-audio -no-window &
	- curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator
	- chmod u+x android-wait-for-emulator
	- ./android-wait-for-emulator
	- adb shell input keyevent 82 &